pipeline:

  build-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t pttg-fs-calc-ui .
    when:
      branch: [master, EE-21542-whitelist-dev-envs]
      event: push

  test:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile_test -t pttg-fs-calc-ui-test .
      - docker run pttg-fs-calc-ui-test
    when:
      event: push

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-fs-calc-ui quay.io/ukhomeofficedigital/pttg-fs-calc-ui:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-fs-calc-ui:build-$${DRONE_BUILD_NUMBER}
    when:
      branch: [master, EE-21542-whitelist-dev-envs]
      event: push

  tag-docker-image-with-git-tag:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-fs-calc-ui quay.io/ukhomeofficedigital/pttg-fs-calc-ui:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/pttg-fs-calc-ui:$${DRONE_TAG}
    when:
      event: tag

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-pttg-fs-calc-ui.git
    when:
      event: [push, deployment, tag]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=pttg-fs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      - WHITELIST=62.25.109.196/32,52.48.127.150/32,52.48.127.151/32,52.48.127.152/32,52.48.127.153/32,52.209.62.128/25,52.56.62.128/25,185.22.224.96,185.22.224.96/32,185.22.226.96/32,213.251.23.180/30,213.251.23.184/30,213.251.23.188/30,148.253.134.213/32,167.98.162.0/25,167.98.158.128/25
    secrets:
      - pttg_fs_dev
    commands:
      - cd kube-pttg-fs-calc-ui
      - ./deploy.sh
    when:
      branch: [master, EE-21542-whitelist-dev-envs]
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=pttg-fs-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      - WHITELIST=62.25.109.196/32,52.48.127.150/32,52.48.127.151/32,52.48.127.152/32,52.48.127.153/32,52.209.62.128/25,52.56.62.128/25,185.22.224.96,185.22.224.96/32,185.22.226.96/32,213.251.23.180/30,213.251.23.184/30,213.251.23.188/30,148.253.134.213/32,167.98.162.0/25,167.98.158.128/25
    secrets:
      - pttg_fs_dev
      - pttg_fs_test
    commands:
      - cd kube-pttg-fs-calc-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, test, preprod]

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=pttg-fs-pr
      - ENVIRONMENT=pr
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
      - WHITELIST=62.25.109.196/24
    secrets:
      - pttg_fs_pr
    commands:
      - cd kube-pttg-fs-calc-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: pr
